/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package createSQL;

import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import createConfig.Config;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
import java.io.StringReader;
import java.nio.file.Files;
import java.util.Iterator;

/**
 *
 * @author cdp
 */
public class create extends javax.swing.JFrame {
    
    private static String searchStart; //fileChooser starts at this directory; from args[0]
    private String dbName;
    private String prefix;   //table names prefix
    private Path templateFile;
    private Path configFile;
    private Path newSQLFile;

    /**
     * Creates new form create
     */
    public create(String searchStart) {
       initComponents();
        searchStart = null; //fileChooser starts at this directory; from args[0]
        dbName = "";
        prefix = "";   //table names prefix
        templateFile = Paths.get("/foo");
        configFile = Paths.get("/foo");
        newSQLFile = Paths.get("/foo");
        setNewSQL();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dbnameLabel = new javax.swing.JLabel();
        dbnameTextField = new javax.swing.JTextField();
        prefixLabel = new javax.swing.JLabel();
        prefixTextField = new javax.swing.JTextField();
        buildButton = new javax.swing.JButton();
        templateButton = new javax.swing.JButton();
        templateLabel = new javax.swing.JLabel();
        configButton = new javax.swing.JButton();
        configLabel = new javax.swing.JLabel();
        newsqlButton = new javax.swing.JButton();
        newsqlLabel = new javax.swing.JLabel();
        newsqlTextField = new javax.swing.JTextField();
        statusLabel = new javax.swing.JLabel();
        greetingsLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Build table creation SQL");

        dbnameLabel.setText("DBname");

        dbnameTextField.setMinimumSize(new java.awt.Dimension(64, 28));
        dbnameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dbnameTextFieldFocusLost(evt);
            }
        });

        prefixLabel.setText("Prefix");

        prefixTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                prefixTextFieldFocusLost(evt);
            }
        });

        buildButton.setText("Build");
        buildButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buildButtonActionPerformed(evt);
            }
        });

        templateButton.setText("Template");
        templateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                templateButtonActionPerformed(evt);
            }
        });

        templateLabel.setText("<- browse for Template");

        configButton.setText("Config");
        configButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configButtonActionPerformed(evt);
            }
        });

        configLabel.setText("<- browse for config file");

        newsqlButton.setText("NewSQL");

        newsqlLabel.setText("new Sql file");

        newsqlTextField.setText("file name");

        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        greetingsLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        greetingsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        greetingsLabel.setText("Build the Tables Creation SQL File");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newsqlButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newsqlLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(newsqlTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dbnameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dbnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(prefixLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prefixTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(templateButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(templateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(configButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(configLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(180, 180, 180)
                                .addComponent(greetingsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 207, Short.MAX_VALUE))
                    .addComponent(statusLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(324, 324, 324)
                .addComponent(buildButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dbnameLabel, prefixLabel});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {configButton, newsqlButton, templateButton});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {configLabel, templateLabel});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(greetingsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dbnameLabel)
                    .addComponent(dbnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prefixLabel)
                    .addComponent(prefixTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(templateButton)
                    .addComponent(templateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(configButton)
                    .addComponent(configLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newsqlButton)
                    .addComponent(newsqlLabel)
                    .addComponent(newsqlTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buildButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buildButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buildButtonActionPerformed
        
          try {
        createNewSQL();
          } catch (IOException IOe) {}

        statusLabel.setText("File " + newSQLFile.getFileName().toString() + " created");
//    JOptionPane.showMessageDialog(null, "DBname:" + dbnameTextField.getText());
    }//GEN-LAST:event_buildButtonActionPerformed

    private void templateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_templateButtonActionPerformed
        JFileChooser fc = new JFileChooser(searchStart);
        fc.setDialogTitle("Where is the template?");
        fc.showOpenDialog(null);
        templateFile = fc.getSelectedFile().toPath();
	templateLabel.setText(templateFile.toString());
    }//GEN-LAST:event_templateButtonActionPerformed

    private void configButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configButtonActionPerformed
        JFileChooser fc = new JFileChooser(searchStart);
	fc.setDialogTitle("Where to put the SQL? (find config file)");
        fc.showOpenDialog(null);
        configFile = fc.getSelectedFile().toPath();
	configLabel.setText(configFile.toString());
//        Config config = new Config(configFile);
        setNewSQL();
    }//GEN-LAST:event_configButtonActionPerformed

    private void dbnameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dbnameTextFieldFocusLost
        dbName = dbnameTextField.getText();
        setNewSQL();
    }//GEN-LAST:event_dbnameTextFieldFocusLost

    private void prefixTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prefixTextFieldFocusLost
        prefix = prefixTextField.getText();
        setNewSQL();
    }//GEN-LAST:event_prefixTextFieldFocusLost

    private void setNewSQL() {
        String fileName;
 
        fileName = "CreateTables_" + dbName + "(";
	if (prefix.isEmpty()) {
		fileName += "no prefix";
	} else {
		fileName += "prefix " + prefix;
	}
	fileName += ").sql";
        newSQLFile = Paths.get(configFile.getParent().toString() + "/" + fileName);
        newsqlLabel.setText(newSQLFile.getParent().toString() + "/");
        newsqlTextField.setText(fileName);
    }
    
    private void createNewSQL() throws IOException {
        Config cl; //The config file reader class
    	BufferedReader templateIn = null;
	BufferedWriter sqlOut = null;
	Iterator<String> iS;
	String aBuffer;
	String aString;

        //The new filename may have been changed:
        newSQLFile = Paths.get(configFile.getParent().toString() + "/" + newsqlTextField.getText());
          try{
        cl = new Config(configFile);
    	cl.load(new StringReader("DBNAME=" + dbName));
    	cl.load(new StringReader("PREFIX=" + prefix));
	templateIn = Files.newBufferedReader(templateFile);
	sqlOut = Files.newBufferedWriter(newSQLFile);
	while ((aBuffer = templateIn.readLine()) != null) {
		iS = cl.stringPropertyNames().iterator();
		while (iS.hasNext()) {
			aString = iS.next();
			aBuffer = aBuffer.replaceAll("<" + aString + ">", cl.getProperty(aString));
		}
		sqlOut.write(aBuffer);
		sqlOut.newLine();
	}
//          } catch (IOException IOe) {
	  } finally {
	if (templateIn != null) {
		templateIn.close();
	}
	if (sqlOut != null) {
		sqlOut.close();
	}
	  } // end try
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                if (args.length > 0) searchStart = args[0];
                /* to set args for Run: in project Properties, choose Run, set arguments*/
                new create(searchStart).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buildButton;
    private javax.swing.JButton configButton;
    private javax.swing.JLabel configLabel;
    private javax.swing.JLabel dbnameLabel;
    private javax.swing.JTextField dbnameTextField;
    private javax.swing.JLabel greetingsLabel;
    private javax.swing.JButton newsqlButton;
    private javax.swing.JLabel newsqlLabel;
    private javax.swing.JTextField newsqlTextField;
    private javax.swing.JLabel prefixLabel;
    private javax.swing.JTextField prefixTextField;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JButton templateButton;
    private javax.swing.JLabel templateLabel;
    // End of variables declaration//GEN-END:variables
}
